### ISSUE TITLE
Auto install a package's dependent tree

### ISSUE THREAD

**Issue by lld2001** [emacscollective/borg#100]
I need to automatically install a package. A package's dependent tree may be lengthy such as `ivy`.  Maybe there are some tricks that I haven't read.

**Comment by tarsius** [comment]
> A package's dependent tree may be lengthy such as `ivy`.

Most of these dependencies are not mandatory and that's one of the reasons why borg does not automatically install dependencies: often it is up to the user to decide which packages to install. In this case for example you may choose not to install `hydra`, in which case it would be advisable to add `ivy-hydra.el` to `submodule.ivy.no-byte-compile` in `.gitmodules`.

**Comment by lld2001** [comment]
Thanks for your tips. 

I'm migrating to `borg` from Doom private config which contain 244 packages right now. I know many of them can be excluded.  But inspect every single package and it's dependency may lead me crazy. 

Could you give me some suggestions about this migrating work.

**Comment by lld2001** [comment]
Do you share your dotemacs publicly? I can't find it in your github repos.

**Comment by tarsius** [comment]
> Could you give me some suggestions about this migrating work.

Compile a list of all package that are installed in your old configuration. Loop over that `borg-assimilate`ing each one. There will be many warnings and errors. Loop again, there should be way fewer warnings now.

> Do you share your dotemacs publicly?

No. It's not really very interesting. It's based on the `all` branch of the `emacs.g` repository.

**Comment by lld2001** [comment]
Thank you. I use this snippet to clone all dependency.
```emacs-lisp
(let* (pkg url)
  (dolist (el '(list of my packages ))
    (setq pkg (epkg (symbol-name el)))
    (setq url (and pkg
		           (if (or (epkg-git-package-p pkg)
			               (epkg-github-package-p pkg)
			               (epkg-orphaned-package-p pkg)
			               (epkg-gitlab-package-p pkg))
		               (eieio-oref pkg 'url)
		             (eieio-oref pkg 'mirror-url))))
    (when url
      (pcase-dolist (`(,orig . ,base) borg-rewrite-urls-alist)
        (when (string-prefix-p orig url)
          (setq url (concat base (substring url (length orig)))))))
    (when url
      (condition-case err
	      (borg-assimilate (symbol-name el) url)
	    ;; The handler.
	    (error                        ; Condition.
	     ;; Display the usual message for this error.
	     (print el)
             (message "%s" (error-message-string err))
	     )))))
```

But the `treemacs` did not correct build. No `.elc` generated.

**Comment by lld2001** [comment]
Maybe the `load-path` of `treemacs` is not correctly set.
```emacs-lisp
(borg-load-path "treemacs")  ;;("e:/emacs/.emacs.d/lib/treemacs/")
                                            ;; should be e:/emacs/.emacs.d/lib/treemacs/src/elisp 
                                            ;; there are some src located in  e:/emacs/.emacs.d/lib/treemacs/src/extra
```
