### ISSUE TITLE
Maybe the borg-load-path  not always work.

### ISSUE THREAD

**Issue by lld2001** [emacscollective/borg#101]
Maybe the `load-path` of `treemacs` is not correctly set.
```emacs-lisp
(borg-load-path "treemacs")  ;;("e:/emacs/.emacs.d/lib/treemacs/")
                                            ;; should be e:/emacs/.emacs.d/lib/treemacs/src/elisp 
                                            ;; there are some src located in  e:/emacs/.emacs.d/lib/treemacs/src/extra
```

```emacs-lisp
(defun borg-load-path (clone)
  "Return the `load-path' for the clone named CLONE."
  (let ((repo (borg-worktree clone))
        (path (borg-get-all clone "load-path")))
    (if  path
        (mapcar (lambda (d) (expand-file-name d repo)) path)
      (let ((elisp (expand-file-name "elisp" repo))
            (lisp (expand-file-name "lisp" repo)))
        (list (cond ((file-exists-p elisp) elisp)
                    ((file-exists-p lisp) lisp)
                    (t repo)))))))
```

In treemacs package, there's an extra `src` directory.

_Originally posted by @lld2001 in https://github.com/emacscollective/borg/issues/100#issuecomment-846674589_

**Comment by tarsius** [comment]
See `submodule.DRONE.load-path` in the manual: https://emacsmirror.net/manual/borg/Variables.html.

**Comment by dakra** [comment]
Maybe it's helpful. You could have a look at [my .gitmodules](https://github.com/dakra/dmacs/blob/8b03fdef4296739c4b2af7f869cff180baf614f9/.gitmodules#L1120)
treemacs secion where I also exclude some extra packages that I don't want.

**Comment by lld2001** [comment]
Thank you. It's very helpful.
