### ISSUE TITLE
New borg install : adding lsp mode - clients are not accessible

### ISSUE THREAD

**Issue by rileyrg** [emacscollective/borg#104]
I just set up my first borg config : I didnt use the seed bootstrap but rather the from scratch method

https://github.com/emacscollective/borg/blob/master/borg.org#bootstrapping-from-scratch

You can see my init.el [here](https://github.com/rileyrg/Emacs-Customisations/blob/borg-full/init.el) 

I went through my config and run borg-assimilate for each use-package and then spent another while doing the same for packages it said was missing when I started emacs up.

All went reasonably well.

But, I'm unable to require any clients from the lib/lsp-mode/clients subdirectory. This results in not being able to install any lsp servers. 

`lsp-auto-configure` is t.

eg (require 'lsp-clangd)

I know I could add this to the path but I would rather not. Is there something I have forgotten (I ran make)? Or is this a problem with lsp autoloads or some such?

**Comment by tarsius** [comment]
You'll have to set the load-path explicitly:

```
[submodule "lsp-mode"]
	path = lib/lsp-mode
	url = git@github.com:emacs-lsp/lsp-mode.git
	load-path = .
	load-path = clients
```
