### ISSUE TITLE
Allow using borg alongside package.el

### ISSUE THREAD

**Issue by tarsius** [emacscollective/borg#11]
`borg` could be used to only install the packages that the user actually works on, while other packages continue to be installed using `package.el`.

* Teach `package.el` about packages installed by `borg`. Because the directories listed in `package-directory-list` are expected to contain package directories of the form `<package>-<version>`, we cannot just add `~/.emacs/lib` to that  list (`borg` only uses `<package>`). We might have to setup a secondary directory containing symlinks. So really we have to teach `borg` about `package.el`.
* Support "clone without assimilation" better.
* ...
* Add `borg` to Melpa.

**Comment by emacs18** [comment]
I have been using emacs for a long time and so had lots of personal customizations. Like many others I converted by setup to use package.el mostly via use-package. In the past few years I generalized my ~/.emacs to optionally enable spacemacs on top of my setup.

Recently I was able to use emacscollective (powered by borg) as well as package.el sufficiently well enough that I was able to get emacs 26 to start up and setup spacemacs along with my own stuff. Over 300 packages are installed. I used borg to install some packages and package.el to install others needed by spacemacs. Now I have the choice of using borg for any number of packages of my choosing, and let pacakge.el handle the rest.

I may get around to providing all the details later, but for now just the key idea is shared. Basically we want to fool package.el into using borg installed packages. I did this by advising package-installed-p and package-activate functions to consider borg packages as detailed below.

I suggested similar solution for straight.el as detailed at https://github.com/raxod502/straight.el/issues/128


```
(defun my-borg-installed-p (package)
  "Return non-nil if PACKAGE is installed by borg."
  (let ((clones (borg-clones))
        (pkg-name (cond
                   ((package-desc-p package)
                    (package-desc-name package))
                   ((symbolp package)
                    (symbol-name package))
                   (t package))))
    (member pkg-name clones)))

(defun my--advice-package-installed-p (original-function &rest args)
  "Return t if package is installed via borg package manager. Otherwise
call the original function `package-installed-p'."
  (or (my-borg-installed-p (car args))
      (apply original-function args)))

(advice-add 'package-installed-p :around 'my--advice-package-installed-p)


(defun my--advice-package-activate (original-function &rest args)
  "Return t if package is installed via `borg' package manager. Otherwise
call the original function `package-activate'."
  (let* ((package (car args))
	 (pkg-name (if (symbolp package) (symbol-name package) package)))
    (if (not (my-borg-installed-p package))
        (apply original-function args)
      ;; Activate borg package it not activated already.
      (unless (member (borg-load-path pkg-name) load-path)
	(borg-activate pkg-name))
      ;; Not sure if package-activated-list needs to be updated here ...
      (unless (memq package package-activated-list)
        (push package package-activated-list))
      t)))

(advice-add 'package-activate :around 'my--advice-package-activate)
```

**Comment by tarsius** [comment]
Closing in favor of #27.
