### ISSUE TITLE
Using borg in existing config

### ISSUE THREAD

**Issue by justbur** [emacscollective/borg#12]
Hi, I'm interested in trying our borg for my config, but it looks like it will be annoying to merge my config with the one in the emacs.g repo. 

I'd ideally like to just replace my package.el code with some borg code. Maybe by adding a borg folder in .emacs.d with the right dependencies. Is there an easy way to do this? I see the manual is structured around cloning .emacs.g and working from there. 

Thanks

**Comment by tarsius** [comment]
It's indeed easiest to get started with `borg` if you have already decided to declare `.emacs.d` bankruptcy anyway. That being said, it's not that hard to merge an Emacs.g branch into an existing configuration. It's also possible to use `package.el` and `borg` together and to gradually migrate to the latter or keep using both. But that is done isn't documented at the moment.

I plan to make it easier to use `borg` for only some packages (i.e. the ones the user had to patch or maintains themselve). See #11.

I was asked about migrating [on Reddit](https://www.reddit.com/r/emacs/comments/60uy4a/borg_manage_packages_as_git_submodules/) before. For now please see that discussion. But feel free to ask follow up questions here.

The essential part of the configuration is this:

```lisp
(add-to-list 'load-path (expand-file-name "lib/borg" user-emacs-directory))
(require  'borg)
(borg-initialize)
```

When initially merging a branch from Emacs.g (likely `master`) or alternatively the [`bootstrap`](https://github.com/emacscollective/bootstrap) configuration, then you most likely won't get any conflicts except for `init.el`. You can discard "their" side and put the above into the existing `init.el` before completing the merge.

If you keep on using `package.el`, then call `package-initialize` *before* the above, to ensure that packages installed with `borg` take precedence over those installed with `package.el`. Also avoid putting other configuration before the above code.

**Comment by justbur** [comment]
Thanks for the explanation(s). I was able to set it up in my config without changing too much, although the code is pretty clunky right now. 

I'm not sure this is for me yet, because it seems labor intensive. I had a few comments/ideas FWIW:

  1. It's a little annoying to me that the packages are built in their respective repos. After assimilating an building a package the repo is almost surely dirty because of either the -autoloads.el file or the .elc files. I then went to automatically update the .gitignore files to ignore these, but conceptually I didn't like that I was adding commits to ignore something in my local build process. 

My thought was: could it somehow work so that the build happens outside of the repos? This would have the advantage of keeping the submodules in sync with their upstream and more "pristine". 

  2. It would also be nice to have a way to replicate melpa-stable-like behavior and have a command to automatically update to commits that have version-like tags. 

In any case, thank you for this it's interesting and useful. I think it accomplishes the goal of allowing complete control over your packages in a reasonably convenient way.

**Comment by tarsius** [comment]
> 1. It's a little annoying to me that the packages are built in their respective repos. After assimilating an building a package the repo is almost surely dirty because of either the -autoloads.el file or the .elc files. I then went to automatically update the .gitignore files to ignore these, but conceptually I didn't like that I was adding commits to ignore something in my local build process.

A few other people have pointed that out before, so there clearly is a need for some documentation here. I didn't document this from the get go because it seems so obvious to me: ignore these files once, globally, and be done with it. Or maybe I will just teach `make bootstrap` to do that.

> 2. It would also be nice to have a way to replicate melpa-stable-like behavior and have a command to automatically update to commits that have version-like tags.

That sounds useful and I will probably add it. Also some other related batch functionality, though some of that will probably be implemented in a generic fashion in magit.

**Comment by tarsius** [comment]
Oh and you will notice that refreshing the status buffer gets rather slow if there are many modules. I started working on that today and discovered some low-hanging fruit. So this should be much less of a problem in a few days.

**Comment by DamienCassou** [comment]
@justbur: I added the following to `~/.config/git/gitignore`:

```gitignore
*.elc
*-autoloads.el
*.info
dir
flycheck_*.el
*-pkg.el
```

**Comment by justbur** [comment]
> A few other people have pointed that out before, so there clearly is a need for some documentation here. I didn't document this from the get go because it seems so obvious to me: ignore these files once, globally, and be done with it. Or maybe I will just teach make bootstrap to do that.

Fair enough. Also, thanks @DamienCassou for the example. I find globally ignoring files a bit odd (bc then you don't necessarily agree with others what a tracked file is), but in this context it's harmless it seems.

> That sounds useful and I will probably add it. Also some other related batch functionality, though some of that will probably be implemented in a generic fashion in magit.

Great, thanks.

**Comment by vkz** [comment]
>Fair enough. Also, thanks @DamienCassou for the example. I find globally ignoring files a bit odd (bc then you don't necessarily agree with others what a tracked file is), but in this context it's harmless it seems.

I thought about globally ignoring those generated files, but then figured another way:
```
git config diff.ignoreSubmodules untracked 
```
See `--ignore-submodules` section in `man git-status` for details. I wonder if it ever comes back to bite me.

**Comment by arichiardi** [comment]
Started to play today with Borg in my super custom Emacs Live conf. 

It is fun. However I could not require any file from things like cider for instance.

I read elsewhere that I can basically just `load-path` Borg and use it in an existing config. Is it fair to say that with that and an assimilate of cider and it's deps I should be able to perform a `(require 'cider)` ?

Am I understanding the moving parts correctly?

**Comment by DamienCassou** [comment]
Andrea Richiardi <notifications@github.com> writes:
> Am I understanding the moving parts correctly?

I don't use Cider but I never had any problem like that with all other
packages I'm using. You have my configuration at
https://github.com/DamienCassou/emacs.d.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by arichiardi** [comment]
Ok I must have done something wrong then. Everything seems similar to what you did there. Thank you for now I will investigate more.

**Comment by arichiardi** [comment]
Officially added `borg` to my soon-to-be-legacy Emacs Live configuration:

https://github.com/arichiardi/clojure-live/tree/borg

:smile: 

Many more questions to come but I love it already!!!

:heart:

**Comment by tarsius** [comment]
I've added some instructions to the manual.

**Comment by arichiardi** [comment]
FYI I was able to solve my problem and I am slowly moving all my packages from Emacs Live to `borg`.

I added this to the mix and it is working like a charm:

https://github.com/arichiardi/emacs.d/blob/master/init.el#L170-L218
