### ISSUE TITLE
Replace `git submodule--helper` subcommands removed/changed in Git 3.38.0

### ISSUE THREAD

**Issue by drot** [emacscollective/borg#131]
`borg.sh` returns: `fatal: 'list' is not a valid submodule--helper subcommand`

Trying the actual command:
```
$ git submodule--helper list
fatal: 'list' is not a valid submodule--helper subcommand
```

Seems like this feature has been removed:
https://github.com/git/git/commit/31955475d1c283120d5d84247eb3fd55d9f5fdd9

**Comment by tarsius** [comment]
> We're not getting anything useful from the "list | cut -f2" invocation that we couldn't get from "foreach 'echo $sm_path'".

Except, the old way is considerably faster:

```
$ time git submodule foreach -q 'echo $sm_path' > /dev/null

real    0m0.585s
user    0m0.413s
sys     0m0.182s

$ time git submodule--helper list > /dev/null

real    0m0.008s
user    0m0.004s
sys     0m0.004s
```

IMO this should be reverted. I'll make that request myself eventually, if nobody beats me to it, but I am quite busy and still trying to take a break, so I would appreciate it if someone else could take care of that.

**Comment by tarsius** [comment]
I've added a code-path, that we will hopefully only need to preserve for this one release.

**Comment by tarsius** [comment]
https://public-inbox.org/git/87czatrpyb.fsf@bernoul.li/T/#u

**Comment by tarsius** [comment]
We are no longer using the removed and changed `git submodule--helper` subcommands.

Some of the alternatives are slower, but from the sound of it we will get replacements eventually.

**Comment by tarsius** [comment]
Borg no longer uses any `git submodule--helper SUBCOMMAND`.
