### ISSUE TITLE
Borg conflict with flymake-mode when editing init.el

### ISSUE THREAD

**Issue by Eason0210** [emacscollective/borg#140]
Hi @tarsius 

I am using Borg with Emacs 29, but flymake-mode will trigger fatal error when editing my init.el file.
I can't reproduce it with `emacs -Q`, and I reported this issue to Emacs two weeks ago , see the [bug#60556](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=60556)

`M-x emacs-version `
`GNU Emacs 29.0.60 (build 1, x86_64-w64-mingw32, git sha1 d0d3451409) of 2023-01-20`

Steps to reproduce the issue:

1.  Install Borg by emacs.g

```
cd ~/.config/
git clone https://github.com/emacscollective/emacs.g.git emacs
cd emacs 
# Need to edit the Makefile to use  main branch instead of master branch, this should also be fixed in emacs.g
# I need use HTTPS instead of SSH
git config --global url.https://github.com/.insteadOf git@github.com:
git config --global url.https://git.sr.ht/.insteadOf git@git.sr.ht:
make bootstrap-borg
make bootstrap
```

2. Start Emacs normally with  `runemacs.exe`
3. M-x `toggle-debug-on-error `
4. `C-x C-f ~/.config/emacs/init.el`, Open init file
5. `M-x flymake-mode`, Enable flymake-mode
6. `M-x flymake-switch-to-log-buffer`, Open the flymake-log buffer
7. `C-x 4 b init.el `, switch to other window with init.el
8. Add some new blank lines in the init.el and `C-x C-s `save the init.el
Now you will see the Warings in the `*Flymake log*` buffer:
```log
 ■  Warning [flymake init.el]: Disabling backend flymake-proc-legacy-flymake because (error Can’t find a suitable init function)
 ■  Warning [elisp-mode init.el]: byte-compile process elisp-flymake-byte-compile obsolete
 ■  Warning [elisp-mode init.el]: byte-compile process elisp-flymake-byte-compile<1> obsolete
 ■  Warning [elisp-mode init.el]: byte-compile process elisp-flymake-byte-compile obsolete
```

In the `*stderr of elisp-flymake-byte-compile*` buffer, there are some errors as bellow:
```log
Initializing drones...done (16 drones in 0.099s)
Initializing drones...done (16 drones in 0.100s)

Warning (initialization): Your `load-path' seems to contain
your `.emacs.d' directory: c:/Users/Eason/.config/emacs/
This is likely to cause problems...
Consider using a subdirectory instead, e.g.: c:/Users/Eason/.config/emacs/lisp

Process elisp-flymake-byte-compile stderr<1> finished

Process elisp-flymake-byte-compile stderr finished
Initializing drones...done (16 drones in 0.100s)

Warning (initialization): Your `load-path' seems to contain
your `.emacs.d' directory: c:/Users/Eason/.config/emacs/
This is likely to cause problems...
Consider using a subdirectory instead, e.g.: c:/Users/Eason/.config/emacs/lisp

Process elisp-flymake-byte-compile stderr finished
```
Sometime will popup and fatal error window as bellow. I also tried to use gdb to debug, see the report at [bug#60556](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=60556)

![image](https://user-images.githubusercontent.com/47546452/213842869-c6d34bde-981e-4936-aed9-699d086441b2.png)

**Comment by tarsius** [comment]
I can reproduce the "Your load-path seems to contain your .emacs.d directory" *warning*. Borg doesn't put that directory on the load-path as far as I can tell. If you figure out that it does in fact do so under certain circumstances, then I would like to hear about it. From the looks of it (as in, I haven't verified it), `flymake` uses in inferior `emacs` instance to do the compilation. Maybe it does that in a way that causes the user directory to be added to the load-path when used with Borg.

I am not interested in using `flymake` and do not have the time to investigate this further. Doing that would require learning about its internals, and I am even less interested in that. As far as I can tell, never having used `flymake` before, it work despite the warning about load-path; things that are wrong seem to get underlined with wiggly lines.

The fatal error hasn't occurred for me. Such an error is always considered a bug in Emacs, even if it is triggered by some third-party elisp, regardless of whether there is a bug in the elisp code too.

**Comment by Eason0210** [comment]
> I am not interested in using `flymake` and do not have the time to investigate this further. Doing that would require learning about its internals, and I am even less interested in that. As far as I can tell, never having used `flymake` before, it work despite the warning about load-path;

Truly understand that.

> The fatal error hasn't occurred for me. Such an error is always considered a bug in Emacs, even if it is triggered by some third-party elisp, regardless of whether there is a bug in the elisp code too.

Agree. Maybe that is somthing wrong with the implementation for displaying on MS-Windows. I tried it on macOS, flymake works well with Borg, although there are  _"Your load-path seems to contain your .emacs.d directory" warning_.

Meawhile, I tried to use `flycheck` instead of `flymake`, It works well with Borg. Recently I will switch to `flycheck `or just turn off `flymake` in my init.el file.

So, feel free to close this issue if you want to. Thanks for your advice!

**Comment by Eason0210** [comment]
Hi @tarsius ，

I can reproduce the issue with `emacs -Q` now. So now I can confirm that the isse is not related to Borg.
Need to use a larger buffer to reproduce, for example, I use the `flmake.el` instead.

Steps to reproduce:

1. Start Emacs 29 with `emacs -Q`
2. `C-c C-f ~/test.el` to open a test buffer.
3. Copy all the content of `flymake.el `to `~/test.el`
4. Enable flymake-mode with `M-x flymake-mode`
5. Try to add some blank lines and then `C-x C-s `to save buffer
6. Repeat step 5 many times, you will get the fatal error window pops up.
![fatal-error-with emacs-q](https://user-images.githubusercontent.com/47546452/213903544-a6dff05b-efa4-45f6-9abb-73cf93fd8c51.png)

**Comment by Eli-Zaretskii** [comment]
Please show the value of `system-configuration-options` inside the session of that Emacs 29.

**Comment by Eason0210** [comment]
Hi @Eli-Zaretskii ，

The value of `system-configuration-options` is `"--without-native-compilation --without-dbus"`

**Comment by Eason0210** [comment]
This issue has been fixed on emacs-29 branch after at commit [c854ef7a18](https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=emacs-29&id=c854ef7a187a579ab1dc7e022a841b59c4361ebf)

Thanks @Eli-Zaretskii for working on it.

**Comment by Eason0210** [comment]
@tarsius 

By the way,   I also figure out that the "Your load-path seems to contain your .emacs.d directory" warning is cause by the variable `elisp-flymake-byte-compile-load-path`.  Because it's default value is `(list "./")`, so when I edit the init.el , the current directory( `~/.config/emacs/` or `~/.emacs.d`) is included to the load path for flyamke.

Just for your information.

**Comment by tarsius** [comment]
Thanks for letting me know. (This seems like something that should be fixed in `flymake`. Complaining about that directory being on the `load-path` is one thing. As is adding it to do the `load-path`. But adding it to the `load-path` and then *also* complaining about it... :grin: )

**Comment by Eason0210** [comment]
> Complaining about that directory being on the `load-path` is one thing. As is adding it to do the `load-path`. But adding it to the `load-path` and then _also_ complaining about it... 😁 )

😁 Make sense! We should improve it before Emacs 29 release.

I have report an issue to Emacs at[ bug#61014](https://debbugs.gnu.org/cgi/bugreport.cgi?bug=61014)
