### ISSUE TITLE
borg.drones-directory with a subfolder, encounter a file missing problem

### ISSUE THREAD

**Issue by YanTree** [emacscollective/borg#144]
## I confirm that...
I have read ["Bootstrapping-from-scratch"](https://emacsmirror.net/manual/borg/Bootstrapping-from-scratch.html), I want to customize the variable of `borg.drones-directory` value, so used command below:
 `git config --local borg.drones-directory "site-lisp/extensions/"`
But there was an unexpected error.
## Steps to reproduce
1. `git config --local borg.drones-directory "site-lisp/extensions/"`
2. `Makefile` keep same from https://emacsmirror.net/manual/borg/Bootstrapping-from-scratch.html
3. `git submodule add --name borg git@github.com:emacscollective/borg.git site-lisp/extensions/borg`
4. `make bootstrap`
5.  Backtrace is shown in the figure below
![image](https://github.com/emacscollective/borg/assets/42629243/f22a527a-257f-4763-aa5d-99cd17b14f18)

## Environment
Emacs: 29.0.92
OS: Win11 22621.1992
Shell: powershell, gitbash

**Comment by tarsius** [comment]
Borg assumes that that directory is a direct subdirectory, at least when setting `borg-drones-directory`, `borg-user-emacs-directory` and `borg-top-level-directory`. Other code might make the same assumption.

Making that assumption makes things simpler, but it should be mentioned in the documentation.

Until now this assumption was not a problem -- it appears you are the first person who would like to use a more deeply nested directory. Is that really important to you? If so, you might have to implement for it yourself.

**Comment by YanTree** [comment]
All right, it's not so important to me. Until now I set `borg.drones-directory` to `modules` instead of a more deeply nested directory, it works perfectly!
