### ISSUE TITLE
Add support for parallel/concurrent builds

### ISSUE THREAD

**Issue by darkfeline** [emacscollective/borg#152]
Apologies if this is a bad request, I have read the docs and skimmed the code and I neither see support for this feature nor any statement that such a feature would not be supported.

I think the request is self-explanatory.

As a naive implementation, this could be done like:

```bash
make -j build/{borg,compat,<all clones here>}

# Add to Makefile:
build/<all other clones>: build/borg build/compat
```

**Comment by tarsius** [comment]
I would recommend against doing this, as it likely brings back the risk of leaking outdated loaded dependencies into the new byte-code.

**Comment by darkfeline** [comment]
IIRC the outdated dependency problem can be solved by adding `(setq load-prefer-newer t)` to `etc/borg/init.el`?

**Comment by tarsius** [comment]
It should help at least. Using `make clean; make -j build/...` would probably be even better.

Please feel free to experiment with such approaches in your configuration (and to share your experience here), but I don't plan to officially support this any time soon.
