### ISSUE TITLE
borg should byte-compile lisp directories recursively

### ISSUE THREAD

**Issue by stepnem** [emacscollective/borg#16]
Some packages split source files into a directory tree. Shouldn't borg compile
them all automatically, or at least optionally? It's what
byte-recompile-directory does, for instance. Currently borg only compiles files
at the top level of a directory.

**Comment by tarsius** [comment]
> Some packages split source files into a directory tree.

Only very few do that.

> Shouldn't borg compile them all automatically, or at least optionally?

You can give borg a list of directories to compile, see https://emacsmirror.net/manual/borg/Git-variables.html.

**Comment by stepnem** [comment]
> You can give borg a list of directories to compile, see https://emacsmirror.net/manual/borg/Git-variables.html.

I know, but IMO recursive compilation by default would be less
surprising behaviour (and an option at least would be more convenient
than editing the config; there are packages with a lot of
subdirectories, see e.g.
<https://github.com/momomo5717/emms-player-mpv-jp-radios>).

**Comment by tarsius** [comment]
> I know, but IMO recursive compilation by default would be less surprising behaviour 

Actually this could lead to very surprising behavior:

1. Some packages, such as `cedet` put libraries in sub-directories but expect only the top-directory to be on the `load path`. Libraries in sub-directories are then loaded using `(require 'package/path/to/library)` , where "package" is on the `load-path` and `library` is a library located in "package/path/to/".

2. Many packages sadly bundle crap libraries and third-party libraries. I have worked to get the maintainers of hundreds of packages to fix that, but this is an issue that will never go away completely. Only adding `lisp/` or if that does not exist the top-directory on the `load-path` bypasses such issues in many cases.

So I think what we currently have is a saver default.

> and an option at least would be more convenient than editing the config

That would mean that you and others would change the value the first time they run into a package for which this would be appropriate to "deal with it once and for all". The disadvantage of that would be that once you install a package as described in (1) or (2) you would be in trouble.

And (as a break from Magit) I am trying a convention-over-configuration approach here, which is another reason I don't want to add an option for this.

**Comment by stepnem** [comment]
Well, you have shifted the issue to load path handling. The original
request was about byte compilation, and I still consider the fact that
borg differs from e.g. byte-recompile-directory here as unfortunate and
perhaps more of a bug than feature request.

As for the load path, your arguments sound fair enough, I guess.

The option (if we are talking about load path handling now) could (or
really should, considering the issues you mention) be per-package,
though. What I meant by "more convenient" is that for packages that have
a lot of subdirs, having to enumerate them all in the config feels
silly, not mentioning the fact that the subdirs might come and go as new
modules are added or removed. It can be automated as everything with
Emacs, of course, but a simple "recurse-subdirs = yes" (in the
particular submodule section, or alternatively a lisp option with the
submodule as the key or something) would seem a good way to handle this.

**Comment by tarsius** [comment]
> Well, you have shifted the issue to load path handling.

Didn't notice. It was late, sorry.

**Comment by tarsius** [comment]
I am unhappy that I made this change even though I don't really believe in it for two reasons. Once I did make the change, I did not hear from you again. I hate it when I do something to make someone happy and because I have undeniable arguments that would speak against doing so, and then that person just goes silent.

And as I had suspected it caused me more pointless work. I have zero packages installed that benefit from this, but at least half a dozen packages that now come with bogus compile-time warnings.

The latter is most likely common, and so I have added `borg-byte-compile-recursively`. Set that to `t` to opt-in to bogus compile-time warnings.

**Comment by stepnem** [comment]
I'm sorry. I was notified of the change, but haven't had the opportunity
to update and react informedly yet (I will certainly do so when I get to
it).

[A response to the rant part of your comment follows:]
In general, if you make any change despite not believing it's the right
thing to do, it will certainly not make _me_ happy either, even if I
happened to like the result. From what I've seen, you as a maintainer
seem to honestly try to consider the input from your users and reach a
consensus and I do appreciate that. On the other hand, there will
certainly be cases when consensus is not to be reached (at least given
the limited resources) and IMO it's then the responsibility of the
maintainer to do what they deem best. (And in the case of Emacs in
particular it's usually not too painful for anybody to modify the source
to their liking if they feel strongly enough about it.)

IOW, if I report an issue, my primary goal is not to get what I want,
but to suggest to the maintainer/community that what I propose is better
than the current state. (Otherwise I could have just modified the
source, and that's what I do if I fail with the above (and haven't
learnt better during the process) or if I don't believe that what I want
is likely to make sense for everybody else.)

In yet another words, honesty (both to oneself and the others) matters
more (to me, anyway) than trying to make anybody happy.

**Comment by tarsius** [comment]
Yeah, I was most annoyed with myself for just implementing this to get it over with and against my better judgement.
