### ISSUE TITLE
Borg can activate modes not supposed to be activated during init-build

### ISSUE THREAD

**Issue by Thaodan** [emacscollective/borg#164]
## Description

While doing `make init-build` loads literally init.el which can activate
functions such as `org-clock-persistence-insinuate` if the user has them in their
configuration which shouldn't be called during batch compilation.

There is no real way to prevent that but it would be useful to be able to apply workaround
such as for example in the case of org-clock to be set `org-clock-persist-fil` to `nil`.

## Steps to reproduce the issue

1. `make init-build V=1`
2. borg calls `borg-batch-rebuild-init` which loads init.el
   literally.
3. Bug is triggered

**Comment by tarsius** [comment]
You should be able to set any lisp variable by adding `--eval ...` to `EMACS_EXTRA` in `borg.mk`. I suppose I could add `TANGLE_EXTRA`, to limit these arguments to `init-tangle`, would that help?

**Comment by Thaodan** [comment]
For tangle there are not issues with init-tangle but with init-build.

**Comment by tarsius** [comment]
I was confused about the "loads literally init.el" and considered asking about that. So you don't create `init.el` from `init.org` (resp. whether you do doesn't matter here)?

I don't understand what kind of change you are asking me to make. Is the `load-file` in `borg-batch-rebuild-init` the problem?

**Comment by Thaodan** [comment]
Jonas Bernoulli ***@***.***> writes:

> I was confused about the "loads literally init.el" and considered
> asking about that. So you don't create `init.el` from `init.org`
> (resp. whether you do doesn't matter here)?

Yes I create init.el from init.org. Loading literally  meant:

> I don't understand what kind of change you are asking me to make. Is the `load-file` in `borg-batch-rebuild-init` the problem?

Yes exactly.

**Comment by tarsius** [comment]
I don't intend to make any changes to what files are loaded when in the short term, but I do plan to eventually look into that again eventually. Given that `init.el` was loaded before being compiled for a long time, means that other people are likely to rely on that (I believe to remember that I do).

**Comment by Thaodan** [comment]
How do they relay on the file being loaded? I thought the file was just
to be byte-compiled.

Any workarounds to the init file being loaded in this case? Check for
batch mode?

**Comment by tarsius** [comment]
> How do they relay on the file being loaded? I thought the file was just to be byte-compiled.

To load things that are required during byte-compilation. I don't remember of the top of my head; maybe adding system-installed packages to the load-path.

> Any workarounds to the init file being loaded in this case? Check for batch mode?

That might work, or patching the function locally.

**Comment by Thaodan** [comment]
Jonas Bernoulli ***@***.***> writes:

>> How do they relay on the file being loaded? I thought the file was just to be byte-compiled.
>
> To load things that are required during byte-compilation. I don't remember of the top of my head; maybe adding system-installed packages to the load-path.

Shouldn't that be done by using extra `EMACS_EXTRA` through borg.mk?

Another option is to override `EMACS_ARGUMENTS` like this:

```make
# Override `EMACS_ARGUMENTS' so it doesn't include -Q and thus loads site-lisp
EMACS_ARGUMENTS := --batch
```

**Comment by tarsius** [comment]
> Shouldn't that [...]

Probably. The point I am trying to make is that things have been for a while as they are now. Changing how this works because it doesn't work for one user comes with the risk of breaking things for other users. I am already aware that I have to rethink how all these files work and plan to do so when I have the time and motivation to do so. That will likely result in a breaking change, so it should be done carefully, to reduce the risk, that there will be multiple breaking changes.

The current setup doesn't work well for anymore either. Despite that I have, and will continue to, tackle other work first. Until then, please work around the issue on your end.
