### ISSUE TITLE
realpath don't works on macOS

### ISSUE THREAD

**Issue by Eason0210** [emacscollective/borg#167]
Hi @tarsius 

With latest version of Borg,`make bootstrap-borg` don't works on macOS anymore, will get the errors as below.
This is because the realpath on macOS is not `grealpath`. 

```
> make bootstrap-borg
realpath: illegal option -- -
usage: realpath [-q] [path ...]
mkdir: /modules: Read-only file system
Cloning into 'lib/borg'...
fatal: Invalid path '/modules': No such file or directory
make: *** [bootstrap-borg] Error 128
```

**Comment by tarsius** [comment]
Could you please find the documentation of this implementation for me?

```
realpath: illegal option -- -
```

That's strange, we are not calling that with `--` or `-` as arguments.

But I guess it boils down to `--relative-to=` not being available. Do you know about another command we could use, which is guaranteed to be available on macOS?

**Comment by Eason0210** [comment]
> But I guess it boils down to `--relative-to=` not being available.

You are right, the `realpath` on macOS do not support `--relative-to=`

**Comment by tarsius** [comment]
Dropped it. See commit for details.
