### ISSUE TITLE
borg-build is (interactive) but only works (if noninteractive)

### ISSUE THREAD

**Issue by thblt** [emacscollective/borg#18]
Following eda44c661c6dff876ccf6bb5d86aafa1e80a546d, the body of `borg-build` is wrapped in `(if noninteractive )`, which basically makes it equivalent to `borg-activate`, which it calls.  I'm not sure I really understand the rationale behind this commit, so I won't offer a PR, but I guess either borg-build should *not* be (interactive), or it should do something meaningful in interactive Emacs. 

Thanks!

**Comment by tarsius** [comment]
The variable `noninteractive` has nothing to do with the `interactive` from that turns a function into a command that can be bound to a key. Emacs is `noninteractive` if it was started using `emacs --batch`. It's a bit unfortunate.

The `(if noninteractive ...)` in `borg-build` does not only have a `THEN` part, it also a `ELSE` part. Which by the way is true for every `if` I ever write. If there is no `ELSE`, then I use `when` instead to make this kind of confusion less likely.

If you take a closer look at the `ELSE`  part you will see that the `THEN` part is actually always executed -- eventually. The `ELSE` part starts a new `noninteractive` Emacs instance using `emacs --batch ...` in which the function `borg-build` is called again. The reason this is being done is that it is the only way to guarantee that no outdated but already loaded code leaks in the byte-compiled code. This is necessary for macros and `defstruct`s and probably other things too.

**Comment by thblt** [comment]
My mistake indeed, I was used to builds blocking Emacs, so was surprised nothing seemed to happen anymore, and obviously misread the code.  Sorry and thanks *a lot* for the detailed explanation, I'll really try not to make such mistakes again.

Yet, I find this new behavior a bit confusing (especially since I use persp-mode, so the new buffer doesn't appear in `C-x b)`.  What do you think of  replacing:

```emacs-lisp
       (generate-new-buffer (format "*Build %s*" drone))
````

with:

``` emacs-lisp
       (switch-to-buffer (generate-new-buffer (format "*Build %s*" drone)))
       ;; or even
       (switch-to-buffer (get-buffer-create (format "*Build %s*" drone)))
```

**Comment by tarsius** [comment]
`borg-build` now reuses a single output buffer and automatically shows it on every build. It can easily be buried using <kbd>C-q</kbd>.
