### ISSUE TITLE
package is outside repository

### ISSUE THREAD

**Issue by DamienCassou** [emacscollective/borg#19]
I have seen this error message twice already, with 2 different packages:

> fatal: /home/cassou/.emacs.d/lib/password-store-otp/: '/home/cassou/.emacs.d/lib/password-store-otp/' is outside repository

**Comment by tarsius** [comment]
Two possible causes come to mind:

1. Something is messed up on the `git` level.
2. Some `borg` function assumes it is being run with `default-directory` being inside `~/.emacs.d/`, but that is not actually the case.

Just in case: what's the `git` release?

**Comment by DamienCassou** [comment]
> Some borg function assumes it is being run with default-directory being inside ~/.emacs.d/, but that is not actually the case

I indeed run `borg` from many different places on my system.

> what's the git release

```
$ git --version
git version 2.13.5
```

**Comment by tarsius** [comment]
> I indeed run `borg` from many different places on my system.

I do that too, this is supposed to not cause any issues -- but there might be a bug (i.e. I forgot to let-bind `default-directory` or something like that).

**Comment by DamienCassou** [comment]
It happened while doing `borg-assimilate`.

**Comment by tarsius** [comment]
(I think you asked me another question about packages on the Emacsmirror. I cannot find it anymore -- please point me to it.)

**Comment by tarsius** [comment]
Has this happened again?

**Comment by DamienCassou** [comment]
Jonas Bernoulli <notifications@github.com> writes:
> Has this happened again?

each time I want to assimilate a submodule and I'm not in ~/.emacs.d.

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill

**Comment by tarsius** [comment]
That sounds fairly reproducible :stuck_out_tongue:  I'll have another look..

**Comment by tarsius** [comment]
Sorry this took so long. Was easy to reproduce too.

**Comment by DamienCassou** [comment]
Jonas Bernoulli <notifications@github.com> writes:
> Sorry this took so long. Was easy to reproduce too.

Thank you very much!

-- 
Damien Cassou
http://damiencassou.seasidehosting.st

"Success is the ability to go from one failure to another without
losing enthusiasm." --Winston Churchill
