### ISSUE TITLE
Document how to recover from missing object

### ISSUE THREAD

**Issue by kevinjfoley** [emacscollective/borg#21]
When running `make bootstrap` on a new machine I'm getting the following error when [nxhtml](https://github.com/emacsorphanage/nxhtml) is initialized:

> fatal: Could not parse object '9726590af3937c6dcd844c1b805ef648938a61fd'.

I understand the hash doesn't exist on the master but I can view it [here](https://github.com/emacsorphanage/nxhtml/tree/9726590af3937c6dcd844c1b805ef648938a61fd).

I'm not really sure what's going on since I've run `make bootstrap` in the past with the same hash and didn't have any problems.  Also I've had this problem with packages outside of emacsorphanage like `spacemacs-theme`.  I'm guessing it stems from me not having a full understand of how `git` is structured.

I'm not sure this is really an issue with `borg` but was hoping someone else here has experienced this and can help me understand what's causing this.

**Comment by tarsius** [comment]
> I'm not really sure what's going

I have switched from a manual import of the last release to an import of the full (mostly meaningless and extremely noisy) history. The latter has the benefit that I am now able to semi-automatically import future upstream changes again (in case that ever happens).

> I understand the hash doesn't exist on the master but I can view it here.

What's most important thing is whether it exists in your local clone. This does not work:

```
% git fetch origin 9726590af3937c6dcd844c1b805ef648938a61fd
error: Server does not allow request for unadvertised object 9726590af3937c6dcd844c1b805ef648938a61fd
```

So you should instead follow the instructions on how to disable a module during bootstrap (basically `git submodule deinit lib/nxhtml`, and then once you have a working Emacs (configured to your needs, except for nxhtml) "update" to the new history.

**Comment by tarsius** [comment]
This should be documented.

**Comment by tarsius** [comment]
"Checking out submodules" on https://emacsmirror.net explains how to deal with failing submodules of `epkgs`. This works mostly the same for failing submodules of `~/.emacs.d`.

**Comment by kevinjfoley** [comment]
> What's most important thing is whether it exists in your local clone. 

That's what I don't get, my understanding is my local clone should contain everything that I can see on GitHub so why is it I can see the commit on GitHub but not locally?  (I know this isn't an issue with `borg` I'm mostly just curious what's going on).

Thanks for the advice, I think I've got things mostly working.

>This should be documented in the manual.

You mean like how to deal with this error if it comes up for others? If so I'd be happy to try to add it and put in a PR.

**Comment by tarsius** [comment]
> That's what I don't get, my understanding is my local clone should contain everything that I can see on GitHub so why is it I can see the commit on GitHub but not locally?

Git only fetches objects that are reachable from some fetched ref. As demonstrated above, it does not even allow fetching some dangling object (an object that is not reachable from some ref) by giving the hash explicitly. It doesn't do so because doing so would be a security risk. Github (the web interface) allows doing it anyway for convenience.

> You mean like how to deal with this error if it comes up for others? If so I'd be happy to try to add it and put in a PR.

Yes. I should probably do that myself though.

**Comment by usharf** [comment]
I'm seeing this, trying to 'make bootstrap'

```
--- [borg] ---

fatal: Could not parse object '454daf91e53e94292a59308c54b251fd83f99464'.
futile: Checkout of '454daf91e53e94292a59308c54b251fd83f99464' into submodule path 'lib/borg' failed
HEAD is now at 362ae8a borg-insert-update-message: New command
lib/borg/borg.mk:66: recipe for target 'bootstrap' failed
make: *** [bootstrap] Error 1
```

**Comment by tarsius** [comment]
By bad, I did not push `borg` but updated `emacs.g`'s `master`. Fixed now.

**Comment by usharf** [comment]
thank you. it's working now.

**Comment by tarsius** [comment]
Tataaa.
(See the manual.)
