### ISSUE TITLE
borg-assimilate fails due to epkg version being too old

### ISSUE THREAD

**Issue by emacs18** [emacscollective/borg#22]
After setting up emacscollective for the first time, executing

```
M-x borg-assimilate
```

resulted in this error message in the mini-buffer:

```
user-error: Please update the ‘epkg’ package.  The installed version is to old for the current database scheme
```

Using edebug I learned that epkg-db-version is 2, but the version returned by the following is 3

```
(caar (emacsql epkg--db-connection "PRAGMA user_version"))
```

Details follow.

On Ubuntu 16.04, I setup emacscollective via

```
$ date
Sun Sep 24 11:30:01 PDT 2017

$ git config --global url.https://github.com/.insteadOf git@github.com:
$ git config --global url.https://gitlab.com/.insteadOf git@gitlab.com:

$ git config --global core.excludesfile ~/.gitignore_global
$ echo '*-autoloads.el' >> ~/.gitignore_global
$ echo '*.elc' >> ~/.gitignore_global
$ echo 'dir' >> ~/.gitignore_global

$ cd ~/Private
$ git clone https://github.com/emacscollective/emacs.g emacs.g2
$ cd emacs.g2
$ make bootstrap
$ mkdir var
$ cd var
$ git clone https://github.com/emacsmirror/epkgs.git

$ rm -rf ~/.emacs.d ~/.emacs
$ ln -s ~/Private/emacs.g2 ~/.emacs.d
```

then launched emacs 25 (I also tried emacs 26 with same result) without
any argument, and tried to execute borg-assimilate.

**Comment by tarsius** [comment]
> Please update the ‘epkg’ package.

Did you try that?

**Comment by emacs18** [comment]
Yes updating epkg does resolve the current issue.

Following is my updated shell script that sets up emacs.g.
Is this really what it takes to setup emacs.g?

Why doesn't the first "make bootstrap" clone the proper files so that 
subsequent "git pull" is not needed?

Do I really need to do "make bootstrap" twice?

```
git config --global url.https://github.com/.insteadOf git@github.com:
git config --global url.https://gitlab.com/.insteadOf git@gitlab.com:

git config --global core.excludesfile ~/.gitignore_global
echo '*-autoloads.el' >> ~/.gitignore_global
echo '*.elc' >> ~/.gitignore_global
echo 'dir' >> ~/.gitignore_global

cd ~/Private
git clone https://github.com/emacscollective/emacs.g emacs.g2
cd emacs.g2

make bootstrap

mkdir var
cd var
git clone https://github.com/emacsmirror/epkgs.git

cd ../lib
(cd auto-compile; git pull)
(cd borg; git pull)
(cd closql; git pull)
(cd dash; git pull)
(cd diff-hl; git pull)
(cd emacsql; git pull)
(cd epkg; git pull)
(cd finalize; git pull)
(cd git-modes; git pull)
(cd magit; git pull)
(cd packed; git pull)
(cd use-package; git pull)
(cd with-editor; git pull)

cd ..
make bootstrap

rm -rf ~/.emacs.d ~/.emacs
ln -s ~/Private/emacs.g2 ~/.emacs.d
```

**Comment by tarsius** [comment]
> Do I really need to do "make bootstrap" twice?

You shouldn't have to do that, and the above output (or "pseudo output"?) doesn't illustrate why it was necessary. I do suspect that it had something to do with `emacs.g`, `epkg` and `epkgs` temporarily being out of sync.

In any case, I do intend to better document how to recover from issue. See #21.
