### ISSUE TITLE
borg-assimilate can't find a git repository

### ISSUE THREAD

**Issue by DamienCassou** [emacscollective/borg#26]
Each time I use `borg-assimilate`, I get the following:

```
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

The trace is

```
Debugger entered--Lisp error: (error "Git failed")
  signal(error ("Git failed"))
  error("Git failed")
  borg--call-git("org-jira" "submodule" "absorbgitdirs" "--" "/home/cassou/.emacs.d/lib/org-jira/")
  borg--maybe-absorb-gitdir("org-jira")
  borg-assimilate("org-jira" "git@github.com:ahungry/org-jira.git" nil)
  funcall-interactively(borg-assimilate "org-jira" "git@github.com:ahungry/org-jira.git" nil)
```

My setup is standard: ~/.emacs.d is a git repository. Moreover, despite the error, it seems that borg happily clones the submodule.

**Comment by tarsius** [comment]
I cannot reproduce this.

* Does the package repository exist before you assimilate it? If so did you create it using `borg-clone` or manually and is `lib/CLONE/.git` a file or a directory before you assimilate?
* Please print the value of `default-directory` at the beginning of `borg--maybe-absorb-gitdir`.

**Comment by tarsius** [comment]
> Moreover, despite the error, it seems that borg happily clones the submodule.

The error happens later when Borg tries to move `~/.emacs.d/lib/DRONE/.git/` to `~/.emacs.d/.git/modules/DRONE/`. (Or in my case `~/.git/modules/emacs.d/modules/DRONE/`, so hairy cases should already being taken care of. But I guess I have to test the non-hairy case to see if I can reproduce it then.)
