### ISSUE TITLE
borg-assimilate fails with "fatal: Not a git repository..."

### ISSUE THREAD

**Issue by NicolasPetton** [emacscollective/borg#3]
My git repository must be in a bad state, but whenever I try to `borg-assimilate` a drone, I got an error message like:

```
fatal: Not a git repository: ../../.git/modules/company-lua
```

My emacs.d is at https://github.com/nicolaspetton/emacs.d

**Comment by tarsius** [comment]
I have gotten errors like this before and it is one of the sharper edges of the modules functionality. You have probably done something wrong, but git doesn't really help you figure out what that is because it bails out very early on.

Check if `~/.emacs.d/.git/modules/company-lua` exists and is a valid gitdir. If not then copy one of the neighboring gitdirs in its place. Now you should at least be able to investigate.

**Comment by NicolasPetton** [comment]
Jonas Bernoulli <notifications@github.com> writes:

I have deleted/cloned my repo, so I won't be able investigate more
unless I face the same issue again.

> Check if `~/.emacs.d/.git/modules/company-lua` exists and is a valid
> gitdir. If not then copy one of the neighboring gitdirs in its
> place. Now you should at least be able to investigate.

The directory existed, and looked like a gitdir.
The weird thing was that I got this issue for any new package I tried to
assimilate, not just company-lua.

**Comment by NicolasPetton** [comment]
@tarsius I got the same error again. It turns out the `.git/modules/PACKAGE` directory contains a `.git` file with the following:

```
gitdir: ../../.git/modules/PACKAGE
```

I have no clue why. After removing this file, it all works fine.

**Comment by tarsius** [comment]
Do you use a very old `git`? I have some vague memory of a bug that caused the creation of such a file.

**Comment by NicolasPetton** [comment]
git version 2.7.5

**Comment by tarsius** [comment]
I was thinking of a different bogus file, see https://github.com/magit/magit/commit/06a7f5230aa720a6c0b9d0c208732bcc81ecc654.

**Comment by tarsius** [comment]
Still it might be worth trying to reproduce this with a more recent version.

**Comment by tarsius** [comment]
Please reopen if you run into this again.
