### ISSUE TITLE
Document preferred workflow for local DRONes

### ISSUE THREAD

**Issue by vkz** [emacscollective/borg#35]
Might not belong in issues per se, but I'm not sure what the best way to communicate things related to Borg might be.

I have a bunch of code that I used to store in my site-lisp/ as local features. These don't necessarily warrant their own repos atm, so I tracked them as part of my emacs.d/. Now that I'm porting my config over to Borg I'm wondering what a preferred workflow for such local code might be. These are usually chunks of code that no longer belong in the init.el proper and may eventually grow into their own packages. Or perhaps you just started putting together your own minor mode or something. To accommodate such cases I used to do the add `site-lisp/*` to the `load-path` dance. Now if you also perform byte-compilation and generate autoloads you'd be pretty much reinventing parts of borg, there must be a better way.

Here's what I did for now

1. mkdir lib/DRONE
2. move relevant code to lib/DRONE
3. make lib/DRONE (this step is easy to forget)
4. now that you byte-compiled and generated autoloads as needed, we have to add the following to init.el:
  ```elisp
(borg-activate "DRONE")
(use-package DRONE :defer t)
```

This seems to work. Is there a better way? 
Could I keep stuff in site-lisp/ and still manage to benefit from Borg somehow or should I not want that? I can certainly figure out a way to do this, but wonder if anyone thought of a systematic way to do so that leverages Borg.

**Comment by vkz** [comment]
To not forget the `make` step above, I put this in as a kludge for now:
```elisp
(defun activate-local-clone (clone)
  (interactive)
  (let* ((path (borg--expand-load-path clone nil))
         (generated-autoload-file
          (expand-file-name (format "%s-autoloads.el" clone) (car path))))
    (unless (file-exists-p generated-autoload-file)
      (borg-build clone)
      (message " Creating %s..." generated-autoload-file))
    (borg-activate clone)))

(activate-local-clone "sexy")
(use-package sexy :defer t)
```

Could be I'm not thinking straight here and really should just separate Emacs proper from what Borg attempts to do. Could've just (load-file ...) and be done.

**Comment by vkz** [comment]
ok,  I feel like I've been digging myself deeper into this local code mess for no good reason. Should probably just `(use-package DRONE :load-path "site-lisp/DRONE")` and be done with it. I ended up reinventing half of Borg but without git submodules, probably running into the same issues you have. Unless someone has interesting ideas, please feel free to close. Apologies for the noise.

**Comment by tarsius** [comment]
I have a local package/drone called `kludges` and put assorted functionality in there. Things keep appearing and disappearing in that package. I also have a assimilated a few packages that I haven't published yet - some of them have already existed for years.

So my recommendation is that you do the same: create one or more packages where you keep your private and/or unfinished tools and assimilate them. There is nothing wrong with doing that and you get all the benefits of `borg` without any additional work.

**Comment by vkz** [comment]
argh, you're right. I should've just tried. Basically I went ahead and created an empty git repo `lib/foo` locally. Magit correctly identified it as a module when I went to commit in emacs.d and now the entire Borg machinery works with this local repo. Thank you

**Comment by tarsius** [comment]
You are welcome!
