### ISSUE TITLE
borg-assimilate fails for symlinked .emacs.d 

### ISSUE THREAD

**Issue by notmgsk** [emacscollective/borg#36]
I have my emacs configuration (using borg) under `~/hackery/emacs.g/`, and have symlinked `~/.emacs.d` to `~/hackery/emacs.g/`. If I invoke emacs with `emacs -q --load ~/hackery/emacs.g/init.el` and then try to `borg-assimilate` all works as expected.

If instead I invoke emacs as `emacs` (letting emacs find `~/.emacs.d/init.el`) and try to `borg-assimilate`, it fails with git saying 
> fatal: Not a git repository: ../../.git/modules/hexcolour

I have tried `(setq vc-follow-symlinks t)` to no avail.

Not sure if this is directly related to #3 or just same error, different cause.

**Comment by tarsius** [comment]
Have a look at `borg-worktree` and `borg-gitdir` (from your description alone I cannot tell where the error occurs) and then also `magit-toplevel` and `magit-git-dir`. As you can see the Magit implementations are much more complex than the `borg` variants.

I would rather not handle this particular special case as that would lead down the path of having to support all the special cases covered by Magit, and that conflicts with my desire to favor conventions over customization.
