### ISSUE TITLE
Making flycheck validate emacs lisp files

### ISSUE THREAD

**Issue by DamienCassou** [emacscollective/borg#38]
Hi,

with borg, flycheck complains about all `require` calls in all emacs lisp files I want to validate. The problem is that flycheck has no clue that package dependencies are in `../`. A workaround is to declare, for each file, a file-local variable for `flycheck-emacs-lisp-load-path`:

```emacs
... a package depending on ivy...
(require 'ivy)
...
;; Local Variables:
;; flycheck-emacs-lisp-load-path: ("../ivy/" ".")
;; End:
```

I don't like this solution because:
1. Emacs complains each time I open the file that setting `flycheck-emacs-lisp-load-path` is unsafe;
2. This footer depends on my own configuration: another maintainer might have problems if she uses another package manager

**Comment by fmdkdd** [comment]
After glancing at the manual, I'm not quite sure I understood where `borg` puts packages, and how it tells Emacs what to load.

If it puts everything under `~/.emacs.d`, why not add all folders in there to the load-path?  Probably this is naive.  

Alternatively, if the `borg` package itself can give you a list of load paths corresponding to the packages loaded in your configuration, then you can use that to automatically set `flycheck-emacs-lisp-load-path` when looking at a file in `~/.emacs.d`.

This could work as a Flycheck extension, similar to what [flycheck-cask](https://github.com/flycheck/flycheck-cask) does.

**Comment by tarsius** [comment]
Borg installs a package in `~/.emacs.d/lib/PACKAGE/`. If `~/.emacs.d/lib/PACKAGE/lisp/` exists, then that is added to the `load-path`, else ``~/.emacs.d/lib/PACKAGE/`. If neither is correct, then the user has to specify the appropriate directory/-ies.


> Alternatively, if the `borg` package itself can give you a list of load paths corresponding to the packages loaded in your configuration, then you can use that to automatically set `flycheck-emacs-lisp-load-path` when looking at a file in `~/.emacs.d`.

A simple implementation could look like:

```lisp
(dolist (drone (borg-drones))
  (dolist (path (borg-load-path drone))
    ...))
```

If you don't want to add every package that is installed using `borg` to the `flycheck` specific `load-path`, then you have to use `epkg-required` to get the list of required packages. That only works for packages known to the Emacsmirror and you might also have to use `epkg-mirrored-package--eieio-childp`.

Also try if #27 does the trick. I don't know what flycheck "normally" does, but if my assumption is correct that it automatically finds packages that are installed using `package`, then teaching `package` about `borg` installed packages might be enough.

**Comment by DamienCassou** [comment]
It seems that 

```emacs
(setq flycheck-emacs-lisp-load-path 'inherit)
```

is enough for me.

**Comment by tarsius** [comment]
I've installed `flycheck` now (but not much experience yet) and I think this setting is good enough for me too.
