### ISSUE TITLE
Remove this dirtyness

### ISSUE THREAD

**Issue by DamienCassou** [emacscollective/borg#4]
When borg compiles and generates autoloads of drones, it makes plenty of them dirty (I guess drone authors should adapt their `.gitignore` file). The magit-status buffer of my `.emacs.d` is unreadable because of this. Is there any workaround beyond submitting PRs to each drone?

**Comment by NicolasPetton** [comment]
I'm facing the exact same problem.

**Comment by NicolasPetton** [comment]
```
	ignore = dirty
```

Did the trick, but I'm not sure it's a good idea.

**Comment by tarsius** [comment]
> Is there any workaround beyond submitting PRs to each drone?

Please don't.

Instead add those two lines to `~/.config/git/ignore` and be done with it forever:

```
*.elc
*-autoloads.el
```

**Comment by NicolasPetton** [comment]
much more reasonable :)

**Comment by NicolasPetton** [comment]
@tarsius however, there are some untracked `dir/` directories as well in some drones.

**Comment by tarsius** [comment]
Those are files. They contain the info manual index for the `*.info` files in the same directory). `dir` is an unfortunate name - nevertheless I suggest you ignore that globally too.

**Comment by tarsius** [comment]
And `*.info` too.

**Comment by DamienCassou** [comment]
Stupid me :-). Thanks.

**Comment by DamienCassou** [comment]
I've just closed it

**Comment by DamienCassou** [comment]
I think we can close this one now.
