### ISSUE TITLE
Get version string for all drones that where updated

### ISSUE THREAD

**Issue by dakra** [emacscollective/borg#42]
I have a lot of packages assimilated so when I update every few days I have 10+ Packages that needs updating.
Updating them is not a problem as I want to see what's new in each anyway, but now the borg documentation says I should write a commit message like:
```
Update 2 drones

Update foo to v1.1.0
Update bar to v1.2.1
```
Is there an easy way to get all version strings of those updated packages?
Copy and pasting from my magit submodules list seems cumbersome with 10+ updated drones.

**Comment by tarsius** [comment]
Yes, I am annoyed by that manual step too.
No, I haven't implemented anything yet.

**Comment by tarsius** [comment]
Ehem. Would you like to do it?

**Comment by dakra** [comment]
> Ehem. Would you like to do it?

Sure. If you tell me how you would do it?
Should I just create a `borg` function that copies all staged drones plus version string to the clipboard? Or directly to the buffer so you can call it inside the commit message buffer? Or just list them "nicely" in magit where the user has to mark and copy himself?
Something else?

**Comment by tarsius** [comment]
> Should I just create a `borg` function that copies all staged drones plus version string to the clipboard? Or directly to the buffer so you can call it inside the commit message buffer?

This is how I would do it.

1. Add a function that returns an alist.
2. Create a function that inserts that at point or "the right place".
3. Make that interactive and bind it in `git-commit-mode`.
4. Add that also to `git-commit-setup-hook`.

Or just list them "nicely" in magit where the user has to mark and copy himself?

That already exists, except that the "Modules overview" section (a child of "Modules") lists all modules, not just the staged once, so you would have to copy several things, not just one block of text. I don't think inserting an alternative, trimmed down and more conveniently formatted section would make much sense once the above functions are implemented.

**Comment by dakra** [comment]
OK, great, I'll see if I can find some time the coming weeks.

One more thing, as `borg` doesn't depend on anything I guess I should just call and parse git myself or do you thing I should depend on magit for that function?
I haven't looked at the code yet so not sure if some magit utility functions even save that much work.

**Comment by tarsius** [comment]
Recently I have been updating the various branches more often so I have implemented this myself now.

Thanks for the nudge 😉

**Comment by dakra** [comment]
Great. Thank you very much :)
