### ISSUE TITLE
Add extra variable for customizations in borg.mk

### ISSUE THREAD

**Issue by dakra** [emacscollective/borg#43]
I need to tangle my org file before I can run the borg init/build functions.
Right now I abuse the SILENCIO variable: https://github.com/dakra/dmacs/blob/86c8c40a54b535bd188a9e01d9c08ce7814aec13/Makefile#L9-L11

I guess this can be made prettier with an empty variable or something in `borg.mk`.
And, unlike `SILENCIO`, this variable should also be appanded to `build-init`.

**Comment by tarsius** [comment]
I think a new `tangle-init` (which has to be called explicitly) would be nicer. It should not unconditionally add `lib/org` to the `load-path` (falling back to the built-in Org). Please experiment with that idea.

**Comment by dakra** [comment]
Good suggestion. It has the slight disadvantage that I have to spawn 2 Emacs processes but it doesn't really take any time compared to the actual compiling.
Now I'm pretty happy with https://github.com/dakra/dmacs/blob/d38702f410b1e05c51d0743e314950518f5aefcc/Makefile#L9-L16

**Comment by tarsius** [comment]
This seems to confirm that the built-in Org is good enough to do the tangling. Good -- if that weren't the case, then that would complicate things.

Does https://github.com/emacscollective/borg/compare/tangle?expand=1 work for you too?

`(expand-file-name "init.org" user-emacs-directory)` won't do the right thing when the super-repository was cloned somewhere different from `~/.emacs.d` for testing purposes. Also it shouldn't be necessary, but please test that.

**Comment by dakra** [comment]
> This seems to confirm that the built-in Org is good enough to do the tangling

Yes. I wasn't even really thinking when I included the `lib/org` path.

> Does https://github.com/emacscollective/borg/compare/tangle?expand=1 work for you too?

Yes, works great. The dependency on `init.org` is nice too, so it only gets tangled when I really update the org file.

> (expand-file-name "init.org" user-emacs-directory) won't do the right thing when the super-repository  was cloned somewhere different from ~/.emacs.d for testing purposes. Also it shouldn't be necessary, but please test that.

Works 👍
