### ISSUE TITLE
clone epkgs.git to ../var/epkgs

### ISSUE THREAD

**Issue by usharf** [emacscollective/borg#48]
I've got things setup per user manual, now trying my first `borg-clone`...

I'm being asked if I want to clone epkgs.git (from emacsmirror) into .emacs.d/var/epkgs ...?
Is this expected? Would appreciate an explanation.

**Comment by tarsius** [comment]
Yes. That repository contains the package database. It is not being tracked as a submodule.

It would be better to clone this during the initial setup on the command-lines and I will add that to the instructions when I finally get around to reworking the documentation.

**Comment by usharf** [comment]
Oh I see. Got it. Thanks !
