### ISSUE TITLE
Nonsilence about unmet assumptions in borg.sh

### ISSUE THREAD

**Issue by whxvd** [emacscollective/borg#53]
Yesterday, I had the recurring problem of being in a drone directory and wanting to (re)compile the drone the Borg way. That usually required to `cd ../..`, `make lib/$drone` and then `cd lib/$drone`, where `$drone` - well - depends on the drone. Most probably I am still missing something from Magit, Borg and/or Emacs that will make this less clumsy. I have only just begun using Magit, and I will find that out on my own.

However, before I realized this, I had already finished:

https://gist.github.com/whxvd/84f2737db850c3e1451ea951a13bb3da

In the process of writing it, I learned more about POSIX compatible shell scripting. And I would like to know from you whether you would like a thorough `... || $eE`-style error catching in `borg.sh`.

The `set -o nounset` at the top is POSIX compliant and it makes the shell bail out on parameter expansions `${X}` if the parameter `X` is not set. But it is possible to have a parameter expansion with a default value, written `${X:-default}`, and the default may be the empty string. `${X:-}` then behaves essentially like `${X}` under `+o nounset`. The only exception that I know of is that an assignment with `${X}` under `+o unset` returns non-zero, if `X` is not set, whereas under `-o unset` it exits the shell if is running a script.

**Comment by tarsius** [comment]
You can `M-x borg-build` to rebuild a drone.

> And I would like to know from you whether you would like a thorough `... || $eE`-style error catching in `borg.sh`.

Seems like overkill but I currently don't have the time to make a fair assessment.

**Comment by tarsius** [comment]
> You can `M-x borg-build` to rebuild a drone.

I think that's good enough.
