### ISSUE TITLE
Proposed way to not autoload pkg but include include in build

### ISSUE THREAD

**Issue by bwolf** [emacscollective/borg#55]
What is the proposed way to not automatically load the autoload file of a package but include the package in the build (make). I would like to avoid the autoload phase, which is done by borg-initialize, by manually setting the path via use-package :load-path "lib/foo/lisp". Any pointers on how to do that or how to implement that. I'm willing to invest some time on it.
To be clear: I see my Emacs spending more and more on autoloads. I already specify via use-package what should trigger a load of the package. But if all the autoload are load beforehand, I see no way to speed this up.

**Comment by tarsius** [comment]
You can explicitly set the build steps for this package and omit `borg-update-autoloads`:

```lisp
[submodule "foobar"]
        build-step = borg-byte-compile
        build-step = borg-makeinfo
```

Assuming that if you don't load the autoloads you are also okay with them not being generated.

**Comment by bwolf** [comment]
Ok, playing with this currently. I'll report my findings. I think this one is a good candidate to be included in the manual.
