### ISSUE TITLE
Borg-assimilate breaks .gitmodules (possibly related to bad indentation)

### ISSUE THREAD

**Issue by thblt** [emacscollective/borg#67]
I'm not sure I really understand how, but `borg-assimilate` often breaks .gitmodules by moving optional fields, like `load-path` to a different section.  I just assimilated `biblio` and `helm-bibtex` and Borg updated `.gitmodules` like this:

``` diff
 modified   .gitmodules
@@ -29,6 +29,9 @@
 [submodule "beginend"]
 	path = lib/beginend
 	url = https://github.com/DamienCassou/beginend
+[submodule "biblio"]
+	path = lib/biblio
+	url = git@github.com:cpitclaudel/biblio.el.git
 [submodule "borg"]
 	path = lib/borg
 	url = https://github.com/emacscollective/borg
@@ -138,10 +141,10 @@
 [submodule "flyspell-correct"]
 	path = lib/flyspell-correct
 	url = https://github.com/d12frosted/flyspell-correct
+load-path = elisp
 [submodule "geiser"]
 	path = lib/geiser
 	url = https://github.com/jaor/geiser.git
-load-path = elisp
 [submodule "general"]
 	path = lib/general
 	url = https://github.com/noctuid/general.el
@@ -166,6 +169,9 @@ load-path = elisp
 [submodule "helm"]
 	path = lib/helm
 	url = https://github.com/emacs-helm/helm
+[submodule "helm-bibtex"]
+	path = lib/helm-bibtex
+	url = git@github.com:tmalsburg/helm-bibtex.git
 [submodule "helm-dash"]
 	path = lib/helm-dash
 	url = https://github.com/areina/helm-dash
new file   lib/biblio
@@ -0,0 +1 @@
+Subproject commit a5a68fcf677f286f205f32dc7486f6c9f66aa6af
new file   lib/helm-bibtex
@@ -0,0 +1 @@
+Subproject commit c591a860bf921eb3353f2ac393b758ac65189af8
```

Notice how `load-path = elisp` moved from `geiser` to `flyspell-correct`.  I suspect this may be related to indentation, but I'm not sure.

(I'm aware this is *not* a good bug report, but I've been experiencing this from some time and I always end up forgetting to open an issue.   I'll try to find a way to reproduce when I'll have more time)

**Comment by tarsius** [comment]
Borg assumes that `variable = value` lines are prefixed with whitespace.

**Comment by thblt** [comment]
Thanks for the clarification.  I assume the assumption is in `borg--sort-submodule-sections`, since the rest of Borg seems to leave git manage the config file itself?
