### ISSUE TITLE
borg-assimilate fails when epkg is not available

### ISSUE THREAD

**Issue by montag451** [emacscollective/borg#68]
When trying to assimilate a package when `epkg` is not available, it fails with `Symbol's function definition is void: epkg`. It seems that `borg-read-package` handles the case where `epkg` is not available but `borg--maybe-confirm-unsafe-action` does not, it blindly calls `epkg` even if the require call fails.

**Comment by tarsius** [comment]
Thanks!

There already was code in that was supposed to make it usable without `epkg`, so I have fixed this by adding another `fboundp`. That also has the advantage that the function at least falls through to the last check, which does not depend on `epkg`.
