### ISSUE TITLE
borg not adding to info-directory-list

### ISSUE THREAD

**Issue by jabranham** [emacscollective/borg#71]
I have auctex assimilated as follows in my `.gitmodules`:

```
[submodule "auctex"]
	path = lib/auctex
	url = https://git.savannah.gnu.org/git/auctex.git
	info-path = doc
	build-step = make extraclean
	build-step = ./autogen.sh
	build-step = ./configure --prefix=$HOME
	build-step = make
	remote = "jabranham git@github.com:jabranham/auctex.git"
```

but `borg-initialize` does not add `/path/to/auctex/doc` to `Info-directory-list`.

**Comment by tarsius** [comment]
Only directories that contain a `dir` file are added. Maybe just `make` doesn't generate and you have to specify some target explicitly?

**Comment by jabranham** [comment]
Ah, I forgot about the `dir` file thing. Yes, it seems to be missing somehow. 

Perhaps add a reminder about this to the borg manual section so that other forgetful users don't complain to you?

Thanks!

**Comment by jabranham** [comment]
Adding `borg-makeinfo` works great, thanks for the tip!

**Comment by tarsius** [comment]
You are welcome!

I reopened to avoid losing track of all the things I have to document. Most open issues actually fall into that category.

**Comment by tarsius** [comment]
I've added a note about this to the manual.
