### ISSUE TITLE
Inconsistent .gitmodules submodule format

### ISSUE THREAD

**Issue by arichiardi** [emacscollective/borg#84]
Hello @tarsius,

I am trying borg in an existing configuration and I am noticing that when I do `borg-assimilate` I get this:

```shell
[submodule "borg"]
	path = lib/borg
	url = git@github.com:emacscollective/borg.git
```

while if I add a submodule with `git submodule add` I get this:

```shell
[submodule "lib/borg"]     <---- different!
	path = lib/borg
	url = git@github.com:emacscollective/borg.git
```

I am wondering if this is ok and what if I have problem with `borg` when trying to add modules manually instead of using `borg-assimilate`.

Thanks!

**Comment by tarsius** [comment]
Use the `--name` argument.
