### ISSUE TITLE
borg-assimilate always tries to clone using git@ protocol

### ISSUE THREAD

**Issue by notmgsk** [emacscollective/borg#87]
See title. If I don't have write access to the repo, trying to clone using `git@` will fail. I can't find how to configure borg so that it prefers `https://` clones.

**Comment by tarsius** [comment]
> If I don't have write access to the repo, trying to clone using `git@` will fail. 

At least for Github and Gitlab It will not fail as long as you have an account and have uploaded your public key.

> I can't find how to configure borg so that it prefers `https://` clones.

It's prominently featured in the manual: https://emacsmirror.net/manual/borg/Installation.html.

**Comment by notmgsk** [comment]
The first suggestion works if and only if your ssh key is unlocked/present in the ssh agent. If this is not the case, borg will not prompt for the ssh key (magit will, however). The second suggestion seems bad: it changes the global config and forces *all* repos to use https.

**Comment by tarsius** [comment]
I have added a new variable `borg-rewrite-urls-alist`. See https://emacsmirror.net/manual/borg/Using-https-URLs.html.
