### ISSUE TITLE
Assumption of borg-gitmodules-file location

### ISSUE THREAD

**Issue by rnkn** [emacscollective/borg#89]
Hello,

I quite like the barebones aesthetic you're going with for Borg.

Borg appears to assume the location of .gitmodules file as the same as borg-user-emacs-directory, which is a fragile assumption because it's contingent on borg-drone-directory, which is arbitrary to wherever the user clones stuff, and because user-emacs-directory is not the root of the git repository necessarily. (e.g. my git repository root is ~/.config and my user-emacs-directory is ~/.config/emacs and I clone packages into ~/.config/emacs/packages.)

I think what you want is (locate-dominating-file borg-user-emacs-directory ".gitmodules") where borg-user-emacs-directory is a defcustom (and ideally borg-drone-directory).

(Sorry this would be a PR instead if I could get Borg going!)

**Comment by rnkn** [comment]
Ah I had another go at this but I see a couple of hardcoded paths. Do these need to be hardcoded?

**Comment by tarsius** [comment]
I have pushed something to the `ancestor` branch.  Please give that a try but note that I haven't tested it at all yet.)

**Comment by rnkn** [comment]
This is still hardcods a "lib" directory...

All cool, I think just the autoloads library will suffice for my needs!
